# Generated by Django 5.2.6 on 2025-10-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='imagen',
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen_mime',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
