# Generated by Django 5.2.7 on 2025-11-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_repartidor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★☆'), (3, '★★★☆☆'), (2, '★★☆☆☆'), (1, '★☆☆☆☆')], default=5)),
                ('comentario', models.TextField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-creado'],
            },
        ),
    ]
