# Generated by Django 5.2.7 on 2025-11-07 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_reseña'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='repartidores_que_rechazaron',
            field=models.ManyToManyField(blank=True, related_name='pedidos_rechazados', to=settings.AUTH_USER_MODEL),
        ),
    ]
