# Generated by Django 5.2.7 on 2025-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_repartidores_que_rechazaron'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='saldo',
            field=models.IntegerField(default=0, help_text='Dinero disponible en la billetera'),
        ),
    ]
